### Written by Donny Kim (dkim8398@sdsu.edu or donnykim27@gmail.com) in June, 2022
### Gegraphy Department, San Diego State University

function [HistoricData_Out, info_Out] = load_IntermediateFiles_Clim(comid)
	
	Path = ['..\out\', comid, '\intermediate']

	% Loading HistoricData
	HistoricData     = load([Path, "HistoricData.mat"]).HistoricData2;
	
	if strcmp(fieldnames(HistoricData), 'PET_monthly') == 1
		HistoricData_Out = struct('precip_monthly', struct2table(HistoricData.precip_monthly),...
								'T_monthly', struct2table(HistoricData.T_monthly),...
								'PET_monthly', struct2table(HistoricData.PET_monthly),...
								'precip_annual', struct2table(HistoricData.precip_annual),...
								'T_annual', struct2table(HistoricData.T_annual),...
								'PET_annual', struct2table(HistoricData.PET_annual),...
								'precip_annual_IMFs', HistoricData.precip_annual_IMFs,...
								'precip_ann_HighFreq', struct2table(HistoricData.precip_ann_HighFreq),...
								'precip_ann_LowFreq', struct2table(HistoricData.precip_ann_LowFreq)
								);
	else
		HistoricData_Out = struct('precip_monthly', struct2table(HistoricData.precip_monthly),...
						'T_monthly', struct2table(HistoricData.T_monthly),...
						'precip_annual', struct2table(HistoricData.precip_annual),...
						'T_annual', struct2table(HistoricData.T_annual),...
						'precip_annual_IMFs', HistoricData.precip_annual_IMFs,...
						'precip_ann_HighFreq', struct2table(HistoricData.precip_ann_HighFreq),...
						'precip_ann_LowFreq', struct2table(HistoricData.precip_ann_LowFreq)
						);
							  
							 
	% Loading info
	info     		= load([Path, "info.mat"]).info2;

	samples = info.SubareaList';
	for i = 1:size(samples, 2);
		temp.(samples{i}) = struct((info.LowFreq_PreAnalysis_Outputs.(samples{i})));
		temp.(samples{i}) = struct2table(temp.(samples{i}));
	end
	temp.TS_rand = info.LowFreq_PreAnalysis_Outputs.TS_rand;
	
	info_Out 		= struct('SubAreaDetails', struct2table(info.SubAreaDetails),...
					'pars', info.pars,...
					%'SubareaList', info.SubareaList,...
					'isOctave', info.isOctave,...
					'LowHighThresh', info.LowHighThresh,...
					'LowFreq_PreAnalysis_Outputs', temp
					);
	info_Out.SubareaList = info.SubareaList; % I don't know why, but if you don't append like this, info becomes 7x1 struct

				   	
end
